name = "OptimPack"
authors = ["Éric Thiébaut <eric.thiebaut@univ-lyon1.fr>"]
uuid = "04a3d532-ba69-5937-989a-472689bdb720"
version = "1.0.0"

[deps]
Compat = "34da2185-b29b-5c13-b0c7-acf172513d20"
Libdl = "8f399da3-3557-5675-b5ff-fb832c97cbdb"
BinaryProvider = "b99e7846-7c00-51b0-8f62-c81ae34c0232"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
